services:
  keyrock:
    image: fiware/idm #:8.1.0-distroless
    #image: keyrock-slim
    hostname: keyrock
    ports:
      - "3005:3005" # localhost:3005
    environment:
      - DEBUG=idm:*
      - IDM_DB_HOST=mysql-db
      - IDM_DB_PASS=secret
      - IDM_DB_USER=root
      - IDM_HOST=http://localhost:3005
      - IDM_PORT=3005
      - IDM_HTTPS_ENABLED=false
      - IDM_HTTPS_PORT=3443
      - IDM_ADMIN_USER=alice
      - IDM_ADMIN_EMAIL=alice-the-admin@test.com
      - IDM_ADMIN_PASS=test

#  orion:
#    image: fiware/orion #:3.0.0
#    hostname: orion
#    command: -dbhost mongo -logLevel DEBUG
#
#  orion-ld:
#    image: fiware/orion-ld:1.0.1
#    hostname: orion-ld
#    command: -dbhost mongo -db orionld -logLevel DEBUG
#
#  orion-proxy:
#    #image: pep-slim
#    image: fiware/pep-proxy #:8.1.0-distroless
#    hostname: orion-proxy
#    ports:
#      - "1027:1027" # localhost:1027
#    environment:
#      - DEBUG=pep-proxy:*
#      - PEP_PROXY_DEBUG=true
#      - PEP_PROXY_APP_HOST=orion
#      - PEP_PROXY_APP_PORT=1026
#      - PEP_PROXY_PORT=1027
#      - PEP_PROXY_IDM_HOST=keyrock
#      - PEP_PROXY_HTTPS_ENABLED=false
#      - PEP_PROXY_AUTH_ENABLED=false
#      - PEP_PROXY_IDM_SSL_ENABLED=false
#      - PEP_PROXY_IDM_PORT=3005
#      - PEP_PROXY_APP_ID=tutorial-dckr-site-0000-xpresswebapp
#      - PEP_PROXY_USERNAME=pep_proxy_00000000-0000-0000-0000-000000000000
#      - PEP_PASSWORD=test
#      - PEP_PROXY_PDP=idm
#      - PEP_PROXY_MAGIC_KEY=1234
#      - PEP_PROXY_PUBLIC_PATHS=/version
#
#  orion-ld-proxy:
#    #image: pep-slim
#    image: fiware/pep-proxy #:8.1.0-distroless
#    hostname: orion-ld-proxy
#    ports:
#      - "1029:1029" # localhost:1029
#    environment:
#      - DEBUG=pep-proxy:*
#      - PEP_PROXY_DEBUG=true
#      - PEP_PROXY_APP_HOST=orion-ld
#      - PEP_PROXY_APP_PORT=1026
#      - PEP_PROXY_PORT=1029
#      - PEP_PROXY_IDM_HOST=keyrock
#      - PEP_PROXY_HTTPS_ENABLED=false
#      - PEP_PROXY_AUTH_ENABLED=false
#      - PEP_PROXY_IDM_SSL_ENABLED=false
#      - PEP_PROXY_IDM_PORT=3005
#      - PEP_PROXY_APP_ID=tutorial-dckr-site-0000-xpresswebapp
#      - PEP_PROXY_USERNAME=pep_proxy_00000000-0000-0000-0000-000000000000
#      - PEP_PASSWORD=test
#      - PEP_PROXY_PDP=idm
#      - PEP_PROXY_MAGIC_KEY=1234
#      - PEP_PROXY_PUBLIC_PATHS=/version

  node-red:
    build: ./node-red
    hostname: node-red
    ports:
      - "8000:1880" # localhost:8000
    volumes:
     - node-red-data:/data

  nr-keyrock-proxy:
    restart: always
    #image: pep-slim
    image: fiware/pep-proxy #:8.1.0-distroless
    hostname: nr-keyrock-proxy
    ports:
      - "1882:1882" # localhost:1882
    environment:
      - DEBUG=pep-proxy:*
      - PEP_PROXY_DEBUG=true
      - PEP_PROXY_APP_HOST=node-red
      - PEP_PROXY_APP_PORT=1880
      - PEP_PROXY_PORT=1882
      - PEP_PROXY_IDM_HOST=keyrock
      - PEP_PROXY_HTTPS_ENABLED=false
      - PEP_PROXY_AUTH_ENABLED=false
      - PEP_PROXY_IDM_SSL_ENABLED=false
      - PEP_PROXY_IDM_PORT=3005
      - PEP_PROXY_APP_ID=tutorial-dckr-site-0000-xpresswebapp
      - PEP_PROXY_USERNAME=pep_proxy_00000000-0000-0000-0000-000000000000
      - PEP_PASSWORD=test
      - PEP_PROXY_PDP=idm
      - PEP_PROXY_MAGIC_KEY=1234
      - PEP_PROXY_PUBLIC_PATHS=/editor,/ui

#  mongo:
#    image: mongo #:4.4
#    hostname: mongo
#    command: --nojournal
#    volumes:
#      - mongo-db:/data/db
#      - mongo-db-config:/data/configdb
#      - ./mongo-config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
#    
#  mongo-express:
#    restart: always
#    image: mongo-express #:1.0.0-alpha
#    ports:
#      - "8081:8081" # localhost:8081

  mysql-db:
    restart: always
    image: mysql:5.7 # compliant with the provided dump
    hostname: mysql-db
    ports:
      - "3306:3306" # localhost:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_ROOT_HOST=%" # Allow any container to access this database
    volumes:
      - mysql-db:/var/lib/mysql
      - ./mysql-data:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
#  mongo-db: ~
#  mongo-db-config: ~
  mysql-db: ~
  node-red-data: ~
