services:
  orion:
    image: fiware/orion #:3.7.0
    hostname: orion
    ports:
      - "1026:1026" # localhost:1026
    command: -dbhost mongo

  orion-ld:
    image: fiware/orion-ld #:1.0.1
    hostname: orion-ld
    ports:
      - "1028:1026" # localhost:1028
    command: -dbhost mongo -db orionld

  mongo:
    image: mongo:5 #:4.4
    hostname: mongo
    command: --nojournal

#  node-red:
#    image: nodered/node-red #:3.0.2
#    hostname: node-red
#    ports:
#      - "1880:1880" # localhost:1880
